sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: xuebaowomenshnag
    region: cn-beijing
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx192f05527fb7fbf0
    secret: 68b6f455d828da867be05db3772c165a
